# DB Settings
spring.h2.console.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/contractgenie
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# General Settings
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
logging.level.org.springframework.security=DEBUG
spring.thymeleaf.check-template-location=false
cors.allowed.origins=http://localhost:4200

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
contractgenie.email.sender=app.finderealty.test@gmail.com

# Open AI Settings
spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.chat.options.model=gpt-4.1

# PG_VECTOR Settings
spring.ai.openai.embedding.options.model=text-embedding-3-large
spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=3072
spring.ai.vectorstore.pgvector.schema-validation=true

# CLOUDINARY SETTINGS
CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}